In [1]:
import numpy as np

# Question 1

In [2]:
A = np.random.rand(35)
A

array([0.77705907, 0.1524523 , 0.69730127, 0.65539378, 0.88934609,
       0.85871369, 0.07135603, 0.68803553, 0.98485819, 0.69192367,
       0.63233043, 0.81164451, 0.16265036, 0.72100076, 0.7427812 ,
       0.77048561, 0.91415767, 0.80714637, 0.26800576, 0.7254081 ,
       0.38400698, 0.24450328, 0.98426679, 0.49675951, 0.06049249,
       0.03891374, 0.62113934, 0.24209686, 0.08576048, 0.42093651,
       0.08379234, 0.66256089, 0.66605277, 0.86127952, 0.94605963])

In [3]:
for x in range(len(A)): 
    if A[x] > .6: 
        print(A[x])

0.7770590676982819
0.6973012748570396
0.6553937841705868
0.8893460930267243
0.8587136941246958
0.6880355301354878
0.9848581948938255
0.6919236724227836
0.6323304349152452
0.8116445052324345
0.7210007645330389
0.7427811994832233
0.7704856054654365
0.914157670404973
0.8071463682257692
0.7254081042633956
0.9842667931449869
0.621139336890205
0.6625608877151458
0.6660527717748809
0.8612795202829662
0.9460596323591758


In [4]:
A = np.square(A)
A

array([0.60382079, 0.0232417 , 0.48622907, 0.42954101, 0.79093647,
       0.73738921, 0.00509168, 0.47339289, 0.96994566, 0.47875837,
       0.39984178, 0.6587668 , 0.02645514, 0.5198421 , 0.55172391,
       0.59364807, 0.83568425, 0.65148526, 0.07182709, 0.52621692,
       0.14746136, 0.05978185, 0.96878112, 0.24677001, 0.00365934,
       0.00151428, 0.38581408, 0.05861089, 0.00735486, 0.17718755,
       0.00702116, 0.43898693, 0.44362629, 0.74180241, 0.89502883])

In [5]:
B = np.reshape(A, (5,7))
B

array([[0.60382079, 0.0232417 , 0.48622907, 0.42954101, 0.79093647,
        0.73738921, 0.00509168],
       [0.47339289, 0.96994566, 0.47875837, 0.39984178, 0.6587668 ,
        0.02645514, 0.5198421 ],
       [0.55172391, 0.59364807, 0.83568425, 0.65148526, 0.07182709,
        0.52621692, 0.14746136],
       [0.05978185, 0.96878112, 0.24677001, 0.00365934, 0.00151428,
        0.38581408, 0.05861089],
       [0.00735486, 0.17718755, 0.00702116, 0.43898693, 0.44362629,
        0.74180241, 0.89502883]])

In [6]:
_ , col = B.shape
for x in range(col): 
    print(np.mean(B[:,x]))

0.33921486146559005
0.5465608207862636
0.41089256916232875
0.3847028644736241
0.3933341873404578
0.4835355509227667
0.3252069722293306


In [7]:
B[:,1] = np.zeros(B[:,1].shape)

In [8]:
for x in range(2,5): 
    B[x-1,:] = 1 

In [9]:
B

array([[0.60382079, 0.        , 0.48622907, 0.42954101, 0.79093647,
        0.73738921, 0.00509168],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.00735486, 0.        , 0.00702116, 0.43898693, 0.44362629,
        0.74180241, 0.89502883]])

In [10]:
A

array([0.60382079, 0.        , 0.48622907, 0.42954101, 0.79093647,
       0.73738921, 0.00509168, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.00735486, 0.        ,
       0.00702116, 0.43898693, 0.44362629, 0.74180241, 0.89502883])

Yes, it did modify the original array. This is due to the the way python handles memory and more specificallym , how Python assigns values to variables. It appears that B is a pointer referencing A so when B is modified, it points to A and thus A is modified as well.

The difference between `numpy.reshape` and `numpy.resize` is that the `resize` directly modifies the original array where `reshape` tries to return a new object but it can also return a copy. 

# Question 2