Ben Kahan  
DS210  
Homework 2  
Collaborators: none

In [1]:
import numpy as np

# Question 1

In [2]:
A = np.random.rand(35)
A

array([0.77705907, 0.1524523 , 0.69730127, 0.65539378, 0.88934609,
       0.85871369, 0.07135603, 0.68803553, 0.98485819, 0.69192367,
       0.63233043, 0.81164451, 0.16265036, 0.72100076, 0.7427812 ,
       0.77048561, 0.91415767, 0.80714637, 0.26800576, 0.7254081 ,
       0.38400698, 0.24450328, 0.98426679, 0.49675951, 0.06049249,
       0.03891374, 0.62113934, 0.24209686, 0.08576048, 0.42093651,
       0.08379234, 0.66256089, 0.66605277, 0.86127952, 0.94605963])

In [3]:
for x in range(len(A)): 
    if A[x] > .6: 
        print(A[x])

0.7770590676982819
0.6973012748570396
0.6553937841705868
0.8893460930267243
0.8587136941246958
0.6880355301354878
0.9848581948938255
0.6919236724227836
0.6323304349152452
0.8116445052324345
0.7210007645330389
0.7427811994832233
0.7704856054654365
0.914157670404973
0.8071463682257692
0.7254081042633956
0.9842667931449869
0.621139336890205
0.6625608877151458
0.6660527717748809
0.8612795202829662
0.9460596323591758


In [4]:
A = np.square(A)
A

array([0.60382079, 0.0232417 , 0.48622907, 0.42954101, 0.79093647,
       0.73738921, 0.00509168, 0.47339289, 0.96994566, 0.47875837,
       0.39984178, 0.6587668 , 0.02645514, 0.5198421 , 0.55172391,
       0.59364807, 0.83568425, 0.65148526, 0.07182709, 0.52621692,
       0.14746136, 0.05978185, 0.96878112, 0.24677001, 0.00365934,
       0.00151428, 0.38581408, 0.05861089, 0.00735486, 0.17718755,
       0.00702116, 0.43898693, 0.44362629, 0.74180241, 0.89502883])

In [5]:
B = np.reshape(A, (5,7))
B

array([[0.60382079, 0.0232417 , 0.48622907, 0.42954101, 0.79093647,
        0.73738921, 0.00509168],
       [0.47339289, 0.96994566, 0.47875837, 0.39984178, 0.6587668 ,
        0.02645514, 0.5198421 ],
       [0.55172391, 0.59364807, 0.83568425, 0.65148526, 0.07182709,
        0.52621692, 0.14746136],
       [0.05978185, 0.96878112, 0.24677001, 0.00365934, 0.00151428,
        0.38581408, 0.05861089],
       [0.00735486, 0.17718755, 0.00702116, 0.43898693, 0.44362629,
        0.74180241, 0.89502883]])

In [6]:
_ , col = B.shape
for x in range(col): 
    print(np.mean(B[:,x]))

0.33921486146559005
0.5465608207862636
0.41089256916232875
0.3847028644736241
0.3933341873404578
0.4835355509227667
0.3252069722293306


In [7]:
B[:,1] = np.zeros(B[:,1].shape)

In [8]:
for x in range(2,5): 
    B[x-1,:] = 1 

In [9]:
B

array([[0.60382079, 0.        , 0.48622907, 0.42954101, 0.79093647,
        0.73738921, 0.00509168],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.00735486, 0.        , 0.00702116, 0.43898693, 0.44362629,
        0.74180241, 0.89502883]])

In [10]:
A

array([0.60382079, 0.        , 0.48622907, 0.42954101, 0.79093647,
       0.73738921, 0.00509168, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.00735486, 0.        ,
       0.00702116, 0.43898693, 0.44362629, 0.74180241, 0.89502883])

Yes, it did modify the original array. This is due to the the way python handles memory and more specificallym , how Python assigns values to variables. It appears that B is a pointer referencing A so when B is modified, it points to A and thus A is modified as well.

The difference between `numpy.reshape` and `numpy.resize` is that the `resize` directly modifies the original array where `reshape` tries to return a new object but it can also return a copy. 

# Question 2

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [17]:
data = pd.read_csv("../homework1/student-mat.csv", sep=";")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

I will choose my last subset from Homework 1 and I removed `freetime` and `sex`. In their places, I added: `higher` and `schoolsup`.  

The subset that I will use for K-means is: `age`, `romantic`, `internet`, `Pstatus`, `health`, `absences`,`goout`, `famsup`, `paid`, `failures`, `higher`, `schoolsup`, and `studytime`. 

In [20]:
data.age.head()

0    18
1    17
2    15
3    15
4    16
Name: age, dtype: int64

In [21]:
data.romantic.head()

0     no
1     no
2     no
3    yes
4     no
Name: romantic, dtype: object

In [22]:
data.internet.head()

0     no
1    yes
2    yes
3    yes
4     no
Name: internet, dtype: object

In [23]:
data.Pstatus.head()

0    A
1    T
2    T
3    T
4    T
Name: Pstatus, dtype: object

In [24]:
data.health.head()

0    3
1    3
2    3
3    5
4    5
Name: health, dtype: int64

In [25]:
data.absences.head()

0     6
1     4
2    10
3     2
4     4
Name: absences, dtype: int64

In [26]:
data.goout.head()

0    4
1    3
2    2
3    2
4    2
Name: goout, dtype: int64

In [27]:
data.famsup.head()

0     no
1    yes
2     no
3    yes
4    yes
Name: famsup, dtype: object

In [28]:
data.paid.head()

0     no
1     no
2    yes
3    yes
4    yes
Name: paid, dtype: object

In [30]:
data.failures.head()

0    0
1    0
2    3
3    0
4    0
Name: failures, dtype: int64

In [31]:
data.higher.head()

0    yes
1    yes
2    yes
3    yes
4    yes
Name: higher, dtype: object

In [32]:
data.schoolsup.head()

0    yes
1     no
2    yes
3     no
4     no
Name: schoolsup, dtype: object

In [33]:
data.studytime.head()

0    2
1    2
2    2
3    3
4    2
Name: studytime, dtype: int64

From the data above, we can see that we need to apply numerical categories to: `romantic`, `internet`, `Pstatus`, `famsup`, `paid`, `higher`, and `schoolsup`.

: `age`, `romantic`, `internet`, `Pstatus`, `health`, `absences`,`goout`, `famsup`, `paid`, `failures`, `higher`, `schoolsup`, and `studytime`. 

In [47]:
selectedData = data[['age', 'romantic', 'internet', 'Pstatus', 'health', 
                     'absences', 'goout', 'famsup', 'paid', 'failures', 'higher',
                     'schoolsup', 'studytime', 'G3']]

In [48]:
selectedData.head()

age romantic internet Pstatus  health  absences  goout famsup paid  \
0   18       no       no       A       3         6      4     no   no   
1   17       no      yes       T       3         4      3    yes   no   
2   15       no      yes       T       3        10      2     no  yes   
3   15      yes      yes       T       5         2      2    yes  yes   
4   16       no       no       T       5         4      2    yes  yes   

   failures higher schoolsup  studytime  G3  
0         0    yes       yes          2   6  
1         0    yes        no          2   6  
2         3    yes       yes          2  10  
3         0    yes        no          3  15  
4         0    yes        no          2  10

In [49]:
binaryFeatures = ['romantic', 'internet', 'Pstatus', 'famsup', 'paid', 'higher', 'schoolsup']

In [50]:
selectedData.romantic = pd.Categorical(selectedData.romantic).codes
selectedData.internet = pd.Categorical(selectedData.internet).codes
selectedData.Pstatus = pd.Categorical(selectedData.Pstatus).codes
selectedData.famsup = pd.Categorical(selectedData.famsup).codes
selectedData.paid = pd.Categorical(selectedData.paid).codes
selectedData.higher = pd.Categorical(selectedData.higher).codes
selectedData.schoolsup = pd.Categorical(selectedData.schoolsup).codes
selectedData.head()

/var/folders/0s/cwxnf6m51pj2nyh3t2ty55gh0000gn/T/ipykernel_32814/2833006768.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selectedData.romantic = pd.Categorical(selectedData.romantic).codes
/var/folders/0s/cwxnf6m51pj2nyh3t2ty55gh0000gn/T/ipykernel_32814/2833006768.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selectedData.internet = pd.Categorical(selectedData.internet).codes
/var/folders/0s/cwxnf6m51pj2nyh3t2ty55gh0000gn/T/ipykernel_32814/2833006768.py:3: SettingWithCopyWarning: 
A value is tr

age  romantic  internet  Pstatus  health  absences  goout  famsup  paid  \
0   18         0         0        0       3         6      4       0     0   
1   17         0         1        1       3         4      3       1     0   
2   15         0         1        1       3        10      2       0     1   
3   15         1         1        1       5         2      2       1     1   
4   16         0         0        1       5         4      2       1     1   

   failures  higher  schoolsup  studytime  G3  
0         0       1          1          2   6  
1         0       1          0          2   6  
2         3       1          1          2  10  
3         0       1          0          3  15  
4         0       1          0          2  10

In [53]:
X,y = selectedData, selectedData.loc[:, ['G3']] # train and test with 2 parameters 
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=.2)